language: java

sudo: required
dist: trusty

matrix:
  include:
    - jdk: oraclejdk11
      env: BUILD_JDK=ORACLE_JDK_11

# https://docs.travis-ci.com/user/languages/java/#maven-dependency-management
install:
  - mvn install -DskipTests=true -B -V -DminimumPriority=1

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2/