version: 1.0.build-{build}
image: Ubuntu2004

# 设置环境变量
environment:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

# 缓存 Maven
cache:
  - /home/appveyor/.gradle/

build_script:
  - sh: chmod +x ./gradlew && ./gradlew bootJar