version: "3"
services:
  nacos-server:
    image: nacos/nacos-server:1.3.1
    container_name: nacos-server
    environment:
      - MODE=standalone
      - NACOS_APPLICATION_PORT=8848
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mariadb
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - 8848:8848
    depends_on:
      - mariadb
    restart: unless-stopped

  redis:
    image: redis:6.0.5
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DATA_DIR}:/data
    restart: unless-stopped

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=65534
      - PGID=100
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${MARIADB_DATA_DIR}:/config
    restart: unless-stopped

  fish-gateway-server:
    image: fish-gateway-server
    container_name: fish-gateway-server
    build:
      context: ./fish-gateway/target
      dockerfile: ../Dockerfile
    ports:
      - 10000:10000
    depends_on:
      - nacos-server
    restart: unless-stopped

  fish-upms-server:
    image: fish-upms-server
    container_name: fish-upms-server
    build:
      context: ./fish-upms/fish-upms-server/target
      dockerfile: ../Dockerfile
    ports:
      - 10100:10100
    depends_on:
      - nacos-server
      - mariadb
      - redis
    restart: unless-stopped

  fish-message-server:
    image: fish-message-server
    container_name: fish-message-server
    build:
      context: ./fish-message/fish-message-server/target
      dockerfile: ../Dockerfile
    ports:
      - 10200:10200
    depends_on:
      - nacos-server
      - redis
    restart: unless-stopped
